# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pagi_pb2 as pagi__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pagi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PagiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AccessMemory = channel.unary_unary(
                '/pagi.Pagi/AccessMemory',
                request_serializer=pagi__pb2.MemoryRequest.SerializeToString,
                response_deserializer=pagi__pb2.MemoryResponse.FromString,
                _registered_method=True)
        self.DelegateRLM = channel.unary_unary(
                '/pagi.Pagi/DelegateRLM',
                request_serializer=pagi__pb2.RLMRequest.SerializeToString,
                response_deserializer=pagi__pb2.RLMResponse.FromString,
                _registered_method=True)
        self.ExecuteAction = channel.unary_unary(
                '/pagi.Pagi/ExecuteAction',
                request_serializer=pagi__pb2.ActionRequest.SerializeToString,
                response_deserializer=pagi__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.SelfHeal = channel.unary_unary(
                '/pagi.Pagi/SelfHeal',
                request_serializer=pagi__pb2.HealRequest.SerializeToString,
                response_deserializer=pagi__pb2.HealResponse.FromString,
                _registered_method=True)
        self.SemanticSearch = channel.unary_unary(
                '/pagi.Pagi/SemanticSearch',
                request_serializer=pagi__pb2.SearchRequest.SerializeToString,
                response_deserializer=pagi__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.ProposePatch = channel.unary_unary(
                '/pagi.Pagi/ProposePatch',
                request_serializer=pagi__pb2.PatchRequest.SerializeToString,
                response_deserializer=pagi__pb2.PatchResponse.FromString,
                _registered_method=True)
        self.ApplyPatch = channel.unary_unary(
                '/pagi.Pagi/ApplyPatch',
                request_serializer=pagi__pb2.ApplyRequest.SerializeToString,
                response_deserializer=pagi__pb2.ApplyResponse.FromString,
                _registered_method=True)
        self.UpsertVectors = channel.unary_unary(
                '/pagi.Pagi/UpsertVectors',
                request_serializer=pagi__pb2.UpsertRequest.SerializeToString,
                response_deserializer=pagi__pb2.UpsertResponse.FromString,
                _registered_method=True)


class PagiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AccessMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DelegateRLM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteAction(self, request, context):
        """Unified action execution schema (Phase 3): enables mockable observability without schema drift.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelfHeal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SemanticSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProposePatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyPatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertVectors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PagiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AccessMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.AccessMemory,
                    request_deserializer=pagi__pb2.MemoryRequest.FromString,
                    response_serializer=pagi__pb2.MemoryResponse.SerializeToString,
            ),
            'DelegateRLM': grpc.unary_unary_rpc_method_handler(
                    servicer.DelegateRLM,
                    request_deserializer=pagi__pb2.RLMRequest.FromString,
                    response_serializer=pagi__pb2.RLMResponse.SerializeToString,
            ),
            'ExecuteAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteAction,
                    request_deserializer=pagi__pb2.ActionRequest.FromString,
                    response_serializer=pagi__pb2.ActionResponse.SerializeToString,
            ),
            'SelfHeal': grpc.unary_unary_rpc_method_handler(
                    servicer.SelfHeal,
                    request_deserializer=pagi__pb2.HealRequest.FromString,
                    response_serializer=pagi__pb2.HealResponse.SerializeToString,
            ),
            'SemanticSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.SemanticSearch,
                    request_deserializer=pagi__pb2.SearchRequest.FromString,
                    response_serializer=pagi__pb2.SearchResponse.SerializeToString,
            ),
            'ProposePatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ProposePatch,
                    request_deserializer=pagi__pb2.PatchRequest.FromString,
                    response_serializer=pagi__pb2.PatchResponse.SerializeToString,
            ),
            'ApplyPatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyPatch,
                    request_deserializer=pagi__pb2.ApplyRequest.FromString,
                    response_serializer=pagi__pb2.ApplyResponse.SerializeToString,
            ),
            'UpsertVectors': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertVectors,
                    request_deserializer=pagi__pb2.UpsertRequest.FromString,
                    response_serializer=pagi__pb2.UpsertResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pagi.Pagi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pagi.Pagi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Pagi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AccessMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pagi.Pagi/AccessMemory',
            pagi__pb2.MemoryRequest.SerializeToString,
            pagi__pb2.MemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DelegateRLM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pagi.Pagi/DelegateRLM',
            pagi__pb2.RLMRequest.SerializeToString,
            pagi__pb2.RLMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pagi.Pagi/ExecuteAction',
            pagi__pb2.ActionRequest.SerializeToString,
            pagi__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelfHeal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pagi.Pagi/SelfHeal',
            pagi__pb2.HealRequest.SerializeToString,
            pagi__pb2.HealResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SemanticSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pagi.Pagi/SemanticSearch',
            pagi__pb2.SearchRequest.SerializeToString,
            pagi__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProposePatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pagi.Pagi/ProposePatch',
            pagi__pb2.PatchRequest.SerializeToString,
            pagi__pb2.PatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyPatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pagi.Pagi/ApplyPatch',
            pagi__pb2.ApplyRequest.SerializeToString,
            pagi__pb2.ApplyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertVectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pagi.Pagi/UpsertVectors',
            pagi__pb2.UpsertRequest.SerializeToString,
            pagi__pb2.UpsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
